// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoPyzzuxnVtdCRiN0doF2swEd7rWCUe3Q',
    appId: '1:728623125675:web:3f4235424401dfd6c893ee',
    messagingSenderId: '728623125675',
    projectId: 'flutter-ipssi',
    authDomain: 'flutter-ipssi.firebaseapp.com',
    storageBucket: 'flutter-ipssi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgMrgokrorq_6CaBm8m-yzY4gfl574Us',
    appId: '1:728623125675:android:1d9521b449411fa1c893ee',
    messagingSenderId: '728623125675',
    projectId: 'flutter-ipssi',
    storageBucket: 'flutter-ipssi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-wctMcWN8NgaA9MPtcTuIKJIc5qAU-E',
    appId: '1:728623125675:ios:ee70a7ce51b874a8c893ee',
    messagingSenderId: '728623125675',
    projectId: 'flutter-ipssi',
    storageBucket: 'flutter-ipssi.appspot.com',
    iosClientId: '728623125675-3ienhjb1id7stkhuflemcuu9num6hg11.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssiBd232',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS-wctMcWN8NgaA9MPtcTuIKJIc5qAU-E',
    appId: '1:728623125675:ios:ee70a7ce51b874a8c893ee',
    messagingSenderId: '728623125675',
    projectId: 'flutter-ipssi',
    storageBucket: 'flutter-ipssi.appspot.com',
    iosClientId: '728623125675-3ienhjb1id7stkhuflemcuu9num6hg11.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssiBd232',
  );
}
