// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUhRENDANaLkefkmwswhyZdy0XmWAcWR0',
    appId: '1:87427743284:web:21e349bc5fce7f8f579461',
    messagingSenderId: '87427743284',
    projectId: 'ipssi2023-7ad45',
    authDomain: 'ipssi2023-7ad45.firebaseapp.com',
    storageBucket: 'ipssi2023-7ad45.appspot.com',
    measurementId: 'G-TS24CTG91V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxAiMlYVAM79km4JSDZ36nEtSNjzaI2ms',
    appId: '1:87427743284:android:3faf93b2c2e36d1f579461',
    messagingSenderId: '87427743284',
    projectId: 'ipssi2023-7ad45',
    storageBucket: 'ipssi2023-7ad45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeC96BSAgLqj3_ZF8B6E8O-C2Gi7qT3Lo',
    appId: '1:87427743284:ios:f0f0ec934d34b101579461',
    messagingSenderId: '87427743284',
    projectId: 'ipssi2023-7ad45',
    storageBucket: 'ipssi2023-7ad45.appspot.com',
    iosClientId: '87427743284-5ng659ddco7irtn17dbt59qfq05dvm65.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssiBd232',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeC96BSAgLqj3_ZF8B6E8O-C2Gi7qT3Lo',
    appId: '1:87427743284:ios:f0f0ec934d34b101579461',
    messagingSenderId: '87427743284',
    projectId: 'ipssi2023-7ad45',
    storageBucket: 'ipssi2023-7ad45.appspot.com',
    iosClientId: '87427743284-5ng659ddco7irtn17dbt59qfq05dvm65.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssiBd232',
  );
}
